import os, json, base64, random, time
from pathlib import Path
from typing import Dict, Any, List, Optional, Tuple
from .schema import (
    LOC15_SCHEMA,
    MAX_OCR_CHARS,
    MAX_OUTPUT_TOKENS,
    DEFAULT_MODEL,
    TIER1_FIELDS,
    TIER2_FIELDS,
    TIER3_FIELDS,
    TIER3_DEFAULTABLE_FIELDS,
    FIELD_PROVENANCE_LABELS,
)

try:
    from openai import OpenAI
except Exception:
    OpenAI = None

class ExtractionFailed(RuntimeError):
    """Extraction did not produce usable metadata.

    Raised instead of returning {} so the caller cannot mistake a failure for a result. The old
    behavior returned an empty dict, which process_path wrote to disk as a full envelope; a resume
    then skipped it because the output file existed. One transient error became one permanent,
    invisible hole in the dataset.
    """


PROMPT_VERSION = "loc15_v4"
_PROMPTS_DIR = Path(__file__).resolve().parent.parent / "prompts"
_CACHED_PROMPTS: Dict[str, Tuple[str, str]] = {}


def _load_prompt(path: Path) -> str:
    if not path.exists():
        raise RuntimeError(f"Prompt file missing: {path}. Ensure prompts/ exists in the repo root.")
    return path.read_text(encoding="utf-8")


def _get_prompts(prompt_version: str = PROMPT_VERSION) -> Tuple[str, str]:
    if prompt_version not in _CACHED_PROMPTS:
        system_prompt_path = _PROMPTS_DIR / f"{prompt_version}_system.txt"
        user_prompt_path = _PROMPTS_DIR / f"{prompt_version}_user.txt"
        _CACHED_PROMPTS[prompt_version] = (
            _load_prompt(system_prompt_path),
            _load_prompt(user_prompt_path),
        )
    return _CACHED_PROMPTS[prompt_version]


def _get_client() -> OpenAI:
    if OpenAI is None:
        raise RuntimeError("openai not installed. pip install openai")
    if not os.getenv("OPENAI_API_KEY"):
        raise RuntimeError("OPENAI_API_KEY not set")
    return OpenAI()

def _clean_metadata(md: Dict[str, Any]) -> Dict[str, Any]:
    """Normalize whitespace without semantic correction."""
    for field, value in list(md.items()):
        if isinstance(value, str):
            trimmed = value.strip()
            md[field] = trimmed if trimmed != "" else None
        elif isinstance(value, list):
            cleaned = []
            for item in value:
                if isinstance(item, str):
                    item = item.strip()
                if item not in [None, ""]:
                    cleaned.append(item)
            md[field] = cleaned
    return md

def _extract_decade(date_value: Optional[str]) -> Optional[str]:
    if not date_value or date_value == "undated":
        return None
    try:
        year = int(str(date_value).split("-")[0])
    except (ValueError, IndexError):
        return None
    decade_start = (year // 10) * 10
    return f"{decade_start}-{decade_start + 9}"

def apply_tier_policy(
    md: Dict[str, Any],
    defaults: Optional[Dict[str, Any]] = None,
) -> Tuple[Dict[str, Any], Dict[str, Dict[str, Any]], Dict[str, str], List[str]]:
    defaults = defaults or {}
    policy_notes: List[str] = []

    allowed_defaults = {
        field: defaults[field]
        for field in TIER3_DEFAULTABLE_FIELDS
        if field in defaults and defaults[field] not in [None, ""]
    }

    for field in TIER3_FIELDS:
        val = md.get(field)
        default_val = allowed_defaults.get(field)
        if default_val is not None:
            if val != default_val:
                md[field] = default_val
                policy_notes.append(f"Applied tier3 default for '{field}'.")
            continue
        if val is None or val == "" or val == [] or val == {}:
            continue
        md[field] = None
        policy_notes.append(f"Cleared tier3 field '{field}' generated by model.")

    decade = _extract_decade(md.get("date")) or md.get("decade")
    if decade and not md.get("decade"):
        md["decade"] = decade

    tier1: Dict[str, Any] = {}
    for field in TIER1_FIELDS:
        if field == "decade":
            tier1[field] = decade
        else:
            tier1[field] = md.get(field)

    tier2 = {field: md.get(field) for field in TIER2_FIELDS}
    tier3 = {field: md.get(field) for field in TIER3_FIELDS}

    field_provenance: Dict[str, str] = {}
    for field in TIER1_FIELDS + TIER2_FIELDS + TIER3_FIELDS:
        field_provenance[field] = FIELD_PROVENANCE_LABELS.get(field, "AI-Generated")

    metadata_tiers = {"tier1": tier1, "tier2": tier2, "tier3": tier3}
    return md, metadata_tiers, field_provenance, policy_notes


def apply_review_overrides(md: Dict[str, Any], review: Dict[str, Any]) -> Tuple[Dict[str, Any], List[str]]:
    overrides = review.get("overrides") or {}
    notes: List[str] = []
    for field in TIER2_FIELDS:
        if field not in overrides:
            continue
        override_val = overrides.get(field)
        if isinstance(override_val, str):
            override_val = override_val.strip()
            if override_val == "":
                override_val = None
        if field in {"subjects", "theme", "genre"}:
            if isinstance(override_val, str):
                parts = [v.strip() for v in override_val.replace("\n", ";").split(";") if v.strip()]
                override_val = parts or None
            elif isinstance(override_val, list):
                cleaned = [str(v).strip() for v in override_val if str(v).strip()]
                override_val = cleaned or None
            else:
                override_val = None
        md[field] = override_val
        notes.append(f"Applied review override for '{field}'.")
    return md, notes

def _image_to_data_url(img_bytes: bytes, mime: str = "image/png") -> str:
    b64 = base64.b64encode(img_bytes).decode("utf-8")
    return f"data:{mime};base64,{b64}"


def default_detail(model: str) -> str:
    """Image fidelity to request.

    'original' preserves input dimensions. Tile-resizing models reduce the shortest side to 768px,
    which destroys the detail this collection needs for accurate name and date readings -- the
    reason the pipeline is on GPT-5.6. See docs/DECISIONS.md D-009.
    """
    return "original" if model.startswith(("gpt-5.6", "gpt-5.4")) else "high"


def _image_part(img_bytes: bytes, mime: str, detail: str) -> Dict[str, Any]:
    image_url: Dict[str, Any] = {"url": _image_to_data_url(img_bytes, mime)}
    if detail:
        image_url["detail"] = detail
    return {"type": "image_url", "image_url": image_url}


# Retry policy. The previous code retried once with no delay, which on a rate limit meant firing
# the same request straight back into the limiter and then giving up -- and a give-up returned {},
# which the caller wrote to disk as a complete-looking output. Over 300 images one 429 became one
# permanent hole that looked processed.
MAX_ATTEMPTS = int(os.getenv("LLM_MAX_ATTEMPTS", "5"))
BACKOFF_BASE_SECONDS = float(os.getenv("LLM_BACKOFF_BASE", "2.0"))
BACKOFF_CAP_SECONDS = float(os.getenv("LLM_BACKOFF_CAP", "60"))

_RETRYABLE_MARKERS = (
    "rate limit", "rate_limit", "429", "too many requests",
    "500", "502", "503", "504", "overloaded", "timeout", "timed out",
    "connection", "temporarily unavailable", "service unavailable",
)


def _is_retryable(error: Exception) -> bool:
    status = getattr(error, "status_code", None) or getattr(error, "http_status", None)
    if isinstance(status, int):
        return status == 429 or status >= 500
    text = str(error).lower()
    return any(marker in text for marker in _RETRYABLE_MARKERS)


def _sleep_backoff(attempt: int, retry_after: Optional[float] = None) -> float:
    """Exponential backoff with full jitter. Honors a server-provided Retry-After when present."""
    if retry_after and retry_after > 0:
        delay = min(float(retry_after), BACKOFF_CAP_SECONDS)
    else:
        delay = min(BACKOFF_BASE_SECONDS * (2 ** attempt), BACKOFF_CAP_SECONDS)
        delay = random.uniform(delay / 2, delay)
    time.sleep(delay)
    return delay


def _retry_after_of(error: Exception) -> Optional[float]:
    response = getattr(error, "response", None)
    headers = getattr(response, "headers", None) or {}
    for key in ("retry-after", "Retry-After", "x-ratelimit-reset-requests"):
        value = headers.get(key) if hasattr(headers, "get") else None
        if value:
            try:
                return float(str(value).rstrip("s"))
            except ValueError:
                continue
    return None


def _completion_kwargs(model: str, max_output_tokens: int, reasoning_effort: str = "") -> Dict[str, Any]:
    """Sampling/limit parameters. GPT-5 models reject temperature/top_p/penalties and use
    max_completion_tokens rather than max_tokens."""
    kwargs: Dict[str, Any] = {"max_completion_tokens": max_output_tokens}
    if reasoning_effort:
        kwargs["reasoning_effort"] = reasoning_effort
    return kwargs


def transcribe_with_model(
    img_bytes: bytes,
    max_chars: int = MAX_OCR_CHARS,
    model: str = DEFAULT_MODEL,
    mime: str = "image/png",
    detail: str = "",
    reasoning_effort: str = "",
) -> Tuple[str, Any]:
    """Vision transcription fallback. Returns (text, usage) so the caller can price the call."""
    client = _get_client()
    detail = detail or default_detail(model)
    resp = client.chat.completions.create(
        model=model,
        messages=[{
            "role": "user",
            "content": [
                {"type": "text", "text": "Transcribe ALL visible text. Preserve line breaks; prefix clearly handwritten lines with '[handwritten] '. Use '[illegible]'/'[unclear]' for unreadable parts. Do not guess at unreadable words. Return PLAIN TEXT only."},
                _image_part(img_bytes, mime, detail),
            ],
        }],
        # 900 was the old cap and is far too low for a reasoning model: on the pilot run 82% of
        # this call's output tokens were reasoning, and several items spent all 900 on reasoning
        # and returned an EMPTY transcript while being billed in full.
        **_completion_kwargs(model, 4000, reasoning_effort),
    )
    text = (resp.choices[0].message.content or "").strip()
    return text[:max_chars], getattr(resp, "usage", None)

def _page_manifest_note(page_labels: List[str]) -> str:
    """Tell the model how many images it is looking at and what to call each one.

    Sent as a separate text part rather than folded into the prompt template, so multi-page support
    works with every prompt version without changing their .format() placeholders.
    """
    listing = "\n".join(f"  Image {i}: {label}" for i, label in enumerate(page_labels, start=1))
    return (
        f"THIS ITEM CONSISTS OF {len(page_labels)} IMAGES, supplied below in order:\n"
        f"{listing}\n\n"
        "They are pages or sides of ONE archival item and must produce ONE metadata record.\n"
        "- Transcribe every image, in this order, each opening with its own [page N] marker on its\n"
        "  own line, where N is the image number above.\n"
        "- Do not emit a separate title, date, or creator per page. Describe the item as a whole:\n"
        "  take the date and signature from whichever page carries them, and note in the\n"
        "  description if pages carry distinct content.\n"
        "- A blank or near-blank side still gets its [page N] marker, followed by [illegible] only\n"
        "  if it has unreadable marks. If it is genuinely blank, write [blank]."
    )


def extract_metadata(
    images: List[Tuple[bytes, str]],
    ocr_text: str,
    filename: str,
    model: str = DEFAULT_MODEL,
    known_collection: str = "",
    known_repository: str = "",
    known_permalink: str = "",
    prompt_version: str = PROMPT_VERSION,
    summary_style_examples: str = "",
    detail: str = "",
    reasoning_effort: str = "",
    usage_sink: Optional[List[Any]] = None,
    page_labels: Optional[List[str]] = None,
) -> Dict[str, Any]:
    """Extract one LOC15 metadata record from one or more images of a single archival item.

    `images` is an ordered list of (bytes, mime) -- pages or sides of the same item. Appends every
    attempt's usage payload to usage_sink if given, so failed and retried attempts are still billed
    accurately.
    """
    client = _get_client()
    detail = detail or default_detail(model)
    ocr_text = (ocr_text or "").strip()[:MAX_OCR_CHARS]
    if not images:
        raise ExtractionFailed("no images supplied")

    system_prompt, user_prompt_template = _get_prompts(prompt_version)
    user_prompt = user_prompt_template.format(
        filename=filename,
        ocr_text=ocr_text if ocr_text else "(none)",
        known_collection=known_collection or "",
        known_repository=known_repository or "",
        known_permalink=known_permalink or "",
        summary_style_examples=summary_style_examples or "No approved summary style examples supplied.",
    )
    content: List[Dict[str, Any]] = [{"type": "text", "text": user_prompt}]
    if len(images) > 1:
        labels = page_labels or [f"image {i}" for i in range(1, len(images) + 1)]
        content.append({"type": "text", "text": _page_manifest_note(labels)})
    for img_bytes, mime in images:
        content.append(_image_part(img_bytes, mime, detail))

    last_error: Optional[str] = None
    for attempt in range(MAX_ATTEMPTS):
        is_last = attempt == MAX_ATTEMPTS - 1
        try:
            resp = client.chat.completions.create(
                model=model,
                messages=[{"role": "system", "content": system_prompt},
                          {"role": "user", "content": content}],
                response_format={
                    "type": "json_schema",
                    "json_schema": {
                        "name": "loc15_metadata",
                        "schema": LOC15_SCHEMA,
                        "strict": True,
                    },
                },
                **_completion_kwargs(model, MAX_OUTPUT_TOKENS, reasoning_effort),
            )
            if usage_sink is not None:
                usage_sink.append(getattr(resp, "usage", None))
            raw = resp.choices[0].message.content or "{}"
            try:
                parsed = json.loads(raw)
                if not parsed:
                    last_error = f"API returned empty metadata. Raw response: {raw[:200]}"
                    if not is_last:
                        delay = _sleep_backoff(attempt)
                        print(f"WARNING: {last_error} Retry {attempt + 2}/{MAX_ATTEMPTS} for "
                              f"{filename} in {delay:.1f}s.")
                        continue
                    raise ExtractionFailed(last_error)
                return _clean_metadata(parsed)
            except json.JSONDecodeError as parse_err:
                print(f"WARNING: JSON parse error for {filename}: {parse_err}")
                i, j = raw.find("{"), raw.rfind("}")
                if i >= 0 and j > i:
                    try:
                        return _clean_metadata(json.loads(raw[i:j + 1]))
                    except Exception:
                        pass
                last_error = f"Could not recover JSON: {parse_err}"
                if not is_last:
                    delay = _sleep_backoff(attempt)
                    print(f"WARNING: {last_error} Retry {attempt + 2}/{MAX_ATTEMPTS} for "
                          f"{filename} in {delay:.1f}s.")
                    continue
                raise ExtractionFailed(last_error)
        except ExtractionFailed:
            raise
        except Exception as exc:
            last_error = f"{type(exc).__name__}: {exc}"
            retryable = _is_retryable(exc)
            if is_last or not retryable:
                raise ExtractionFailed(
                    f"{last_error}" + ("" if retryable else " (not retryable)")
                ) from exc
            delay = _sleep_backoff(attempt, _retry_after_of(exc))
            print(f"WARNING extracting metadata for {filename}: {last_error}. "
                  f"Retry {attempt + 2}/{MAX_ATTEMPTS} in {delay:.1f}s.")

    raise ExtractionFailed(last_error or "exhausted retries")
